{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/profile","error":"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"},"timestamp":"2025-06-25 10:09:20,046+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/profile","error":"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"},"timestamp":"2025-06-25 10:18:24,411+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/options-chain-v3","error":"('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"},"timestamp":"2025-06-25 10:19:00,639+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/options-chain-v3","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Read timed out. (read timeout=None)"},"timestamp":"2025-06-25 10:20:07,283+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/profile","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /api/v3/profile (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000240AEFD8560>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-06-25 10:20:19,493+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/depth","Error":{"message":"Please provide valid inputs","code":-50,"s":"error"}},"timestamp":"2025-06-30 11:29:21,536+0530","service":"FyersAPI"}
